name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/admin/projects/PerplexityUnified
            git pull origin main
            if [ -f package-lock.json ]; then
              npm ci
            fi
            echo "Clean build started"
            npm run build
            pm2 restart all
